all: TEAE01_rapport.pdf

TEAE01_rapport.pdf: TEAE01_rapport.tex
	pdflatex TEAE01_rapport.tex && \
	pdflatex TEAE01_rapport.tex && \
	pdflatex TEAE01_rapport.tex

clean:
	rm -f TEAE01_rapport.toc TEAE01_rapport.log TEAE01_rapport.aux TEAE01_rapport.pdf


